title: "Monitoring Cells with Prometheus & Grafana"
abstract: "Enable metrics with prometheus and grafana"
language: und
category: Deployment
tags:
  - cells
  - configuration
  - dataviz
  - enterprise distribution
  - grafana
  - metrics
  - prometheus
